# Generated by Django 5.2.3 on 2025-06-18 13:30

import django.db.models.deletion
import time
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("version", models.FloatField(default=time.time)),
                ("timer_type", models.CharField(max_length=50)),
                ("seconds", models.IntegerField()),
                ("auto_pass", models.BooleanField(default=False)),
                (
                    "active_player_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("any_timer_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("player_id", models.IntegerField()),
                ("timer_state", models.JSONField()),
                (
                    "game_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game_sessions.gamesession",
                    ),
                ),
            ],
        ),
    ]
